name: Usage Analytics Workflow

on: workflow_dispatch

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python data-extraction.py

      - name: Run validation script
        run: python metric-validation.py

      - name: Run post-processing script
        run: python post-processing.py

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: Aaquiff
          minimum-approvals: 1
          issue-title: "Approval required to proceed with release"
          issue-body: "Please approve to continue to the release step."

      - name: Run release-ready script
        run: python release_ready.py
